scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Adele/Rumour Has It - Single/01 Rumour Has It.m4a" "import/./Adele/Rumour Has It - Single/01 Rumour Has It.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Barr Brothers/The Barr Brothers/01 Beggar In the Morning 1.m4a" "import/./The Barr Brothers/The Barr Brothers/01 Beggar In the Morning 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Barr Brothers/The Barr Brothers/01 Beggar In the Morning.m4a" "import/./The Barr Brothers/The Barr Brothers/01 Beggar In the Morning.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Coldplay/Ghost Stories/01 Always In My Head.m4a" "import/./Coldplay/Ghost Stories/01 Always In My Head.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Michael Bublé/Cold December Night - Single/01 Cold December Night.m4a" "import/./Michael Bublé/Cold December Night - Single/01 Cold December Night.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Minor Alps/Get There/02 I Don't Know What to Do With My Hands.m4a" "import/./Minor Alps/Get There/02 I Don't Know What to Do With My Hands.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Iron & Wine/Grace for Saints and Ramblers - Single/01 Grace for Saints and Ramblers.m4a" "import/./Iron & Wine/Grace for Saints and Ramblers - Single/01 Grace for Saints and Ramblers.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Iron & Wine/Grace for Saints and Ramblers - Single/01 Grace for Saints and Ramblers 1.m4a" "import/./Iron & Wine/Grace for Saints and Ramblers - Single/01 Grace for Saints and Ramblers 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Twin Forks/Twin Forks/01 Can't Be Broken.m4a" "import/./Twin Forks/Twin Forks/01 Can't Be Broken.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Diego Garcia/You Were Never There - Single/01 You Were Never There.m4a" "import/./Diego Garcia/You Were Never There - Single/01 You Were Never There.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Avett Brothers/I and Love and You - Single/01 I and Love and You.m4p" "import/./The Avett Brothers/I and Love and You - Single/01 I and Love and You.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Avett Brothers/Live and Die - Single/01 Live and Die.m4a" "import/./The Avett Brothers/Live and Die - Single/01 Live and Die.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Avett Brothers/Live and Die - Single/01 Live and Die 1.m4a" "import/./The Avett Brothers/Live and Die - Single/01 Live and Die 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Gomez/A New Tide/11 Sunset Gates.m4p" "import/./Gomez/A New Tide/11 Sunset Gates.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Brandi Carlile/The Firewatcher's Daughter/01 Wherever Is Your Heart.m4a" "import/./Brandi Carlile/The Firewatcher's Daughter/01 Wherever Is Your Heart.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Brandi Carlile/Give Up the Ghost/02 Dying Day.m4a" "import/./Brandi Carlile/Give Up the Ghost/02 Dying Day.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./James Taylor/Before This World/01 Today Today Today.m4a" "import/./James Taylor/Before This World/01 Today Today Today.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Miguel/Kaleidoscope Dream/01 Adorn.m4a" "import/./Miguel/Kaleidoscope Dream/01 Adorn.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Miguel/Kaleidoscope Dream/01 Adorn 1.m4a" "import/./Miguel/Kaleidoscope Dream/01 Adorn 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Macklemore & Ryan Lewis/The Heist/05 Same Love (feat. Mary Lambert) 1.m4a" "import/./Macklemore & Ryan Lewis/The Heist/05 Same Love (feat. Mary Lambert) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Macklemore & Ryan Lewis/The Heist/05 Same Love (feat. Mary Lambert).m4a" "import/./Macklemore & Ryan Lewis/The Heist/05 Same Love (feat. Mary Lambert).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Macklemore & Ryan Lewis/The Heist/05 Same Love (feat. Mary Lambert) 2.m4a" "import/./Macklemore & Ryan Lewis/The Heist/05 Same Love (feat. Mary Lambert) 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Other Lives/Black Tables - Single/01 Black Tables.m4a" "import/./Other Lives/Black Tables - Single/01 Black Tables.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Black Keys/Turn Blue/03 Turn Blue.m4a" "import/./The Black Keys/Turn Blue/03 Turn Blue.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Black Keys/Run Right Back - Single/01 Run Right Back.m4a" "import/./The Black Keys/Run Right Back - Single/01 Run Right Back.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Black Keys/Run Right Back - Single/01 Run Right Back 1.m4a" "import/./The Black Keys/Run Right Back - Single/01 Run Right Back 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Civil Wars/The Civil Wars/04 Dust to Dust.m4a" "import/./The Civil Wars/The Civil Wars/04 Dust to Dust.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jimmy Greene/Beautiful Life/04 Ana's Way (feat. Kurt Elling).m4a" "import/./Jimmy Greene/Beautiful Life/04 Ana's Way (feat. Kurt Elling).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dum Dum Girls/Too True/04 Are You Okay_.m4a" "import/./Dum Dum Girls/Too True/04 Are You Okay_.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Natalie Maines/Mother/10 Take It On Faith.m4a" "import/./Natalie Maines/Mother/10 Take It On Faith.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Shakey Graves/Dearly Departed (feat. Esmé Patterson) - Single/01 Dearly Departed (feat. Esmé Patterson).m4a" "import/./Shakey Graves/Dearly Departed (feat. Esmé Patterson) - Single/01 Dearly Departed (feat. Esmé Patterson).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Shakey Graves/And the War Came/03 Dearly Departed (feat. Esmé Patterson).m4a" "import/./Shakey Graves/And the War Came/03 Dearly Departed (feat. Esmé Patterson).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./City and Colour/Fragile Bird - Single/01 Fragile Bird.m4a" "import/./City and Colour/Fragile Bird - Single/01 Fragile Bird.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./City and Colour/Fragile Bird - Single/01 Fragile Bird 1.m4a" "import/./City and Colour/Fragile Bird - Single/01 Fragile Bird 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Gossip/Music for Men (Deluxe Version)/02 Heavy Cross.m4a" "import/./Gossip/Music for Men (Deluxe Version)/02 Heavy Cross.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Arcade Fire/Reflektor/1-01 Reflektor.m4a" "import/./Arcade Fire/Reflektor/1-01 Reflektor.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Decemberists/The Rake's Song - Single/01 The Rake's Song.m4a" "import/./The Decemberists/The Rake's Song - Single/01 The Rake's Song.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Greg Laswell/Three Flights from Alto Nido/05 How the Day Sounds.m4a" "import/./Greg Laswell/Three Flights from Alto Nido/05 How the Day Sounds.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Steel Magnolia/Keep On Lovin' You - Single/01 Keep On Lovin' You 1.m4a" "import/./Steel Magnolia/Keep On Lovin' You - Single/01 Keep On Lovin' You 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Steel Magnolia/Keep On Lovin' You - Single/01 Keep On Lovin' You.m4a" "import/./Steel Magnolia/Keep On Lovin' You - Single/01 Keep On Lovin' You.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Postal Service/Give Up (Deluxe 10th Anniversary Edition)/1-02 Such Great Heights 1.m4a" "import/./The Postal Service/Give Up (Deluxe 10th Anniversary Edition)/1-02 Such Great Heights 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Postal Service/Give Up (Deluxe 10th Anniversary Edition)/1-02 Such Great Heights.m4a" "import/./The Postal Service/Give Up (Deluxe 10th Anniversary Edition)/1-02 Such Great Heights.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Kelis/Food/01 Jerk Ribs.m4a" "import/./Kelis/Food/01 Jerk Ribs.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Mikal Cronin/MCIII/01 Turn Around.m4a" "import/./Mikal Cronin/MCIII/01 Turn Around.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Mumlers/Don't Throw Me Away (Bonus Track Version)/03 Tangled Up With You.m4a" "import/./The Mumlers/Don't Throw Me Away (Bonus Track Version)/03 Tangled Up With You.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Marie & the redCat/Home/08 Beautiful Day.m4a" "import/./Marie & the redCat/Home/08 Beautiful Day.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ian Axel/This Is the New Year/06 This Is the New Year (feat. Chad Vaccarino).m4a" "import/./Ian Axel/This Is the New Year/06 This Is the New Year (feat. Chad Vaccarino).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Thievery Corporation/Hare Krisna-Single/01 Hare Krisna 2.m4p" "import/./Thievery Corporation/Hare Krisna-Single/01 Hare Krisna 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Carole King/Everyday Will Be Like a Holiday - Single/01 Everyday Will Be Like a Holiday.m4a" "import/./Carole King/Everyday Will Be Like a Holiday - Single/01 Everyday Will Be Like a Holiday.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Carole King/Everyday Will Be Like a Holiday - Single/01 Everyday Will Be Like a Holiday 1.m4a" "import/./Carole King/Everyday Will Be Like a Holiday - Single/01 Everyday Will Be Like a Holiday 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Slow Club/Wanderer Wandering - Single/01 Wanderer Wandering.m4a" "import/./Slow Club/Wanderer Wandering - Single/01 Wanderer Wandering.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jim James/Regions of Light and Sound of God/04 A New Life.m4a" "import/./Jim James/Regions of Light and Sound of God/04 A New Life.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jim James/Regions of Light and Sound of God/04 A New Life 2.m4a" "import/./Jim James/Regions of Light and Sound of God/04 A New Life 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jim James/Regions of Light and Sound of God/04 A New Life 1.m4a" "import/./Jim James/Regions of Light and Sound of God/04 A New Life 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Holly Miranda/The Magician's Private Library (Bonus Track Version)/03 Waves.m4a" "import/./Holly Miranda/The Magician's Private Library (Bonus Track Version)/03 Waves.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sturgill Simpson/Metamodern Sounds in Country Music/08 Just Let Go.m4a" "import/./Sturgill Simpson/Metamodern Sounds in Country Music/08 Just Let Go.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Tragically Hip/We Are the Same (Bonus Track Version)/04 Coffee Girl.m4a" "import/./The Tragically Hip/We Are the Same (Bonus Track Version)/04 Coffee Girl.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Great Lake Swimmers/Lost Channels/09 Still.m4a" "import/./Great Lake Swimmers/Lost Channels/09 Still.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ben Harper & Charlie Musselwhite/Get Up! (Deluxe Version)/05 You Found Another Lover (I Lost Another Friend).m4a" "import/./Ben Harper & Charlie Musselwhite/Get Up! (Deluxe Version)/05 You Found Another Lover (I Lost Another Friend).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ben Harper & Charlie Musselwhite/Get Up! (Deluxe Version)/05 You Found Another Lover (I Lost Another Friend) 1.m4a" "import/./Ben Harper & Charlie Musselwhite/Get Up! (Deluxe Version)/05 You Found Another Lover (I Lost Another Friend) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Gregory Porter/Liquid Spirit/05 Hey Laura.m4a" "import/./Gregory Porter/Liquid Spirit/05 Hey Laura.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Hot Sardines/The Hot Sardines/03 Wake Up In Paris.m4a" "import/./The Hot Sardines/The Hot Sardines/03 Wake Up In Paris.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Frazey Ford/Indian Ocean/01 September Fields.m4a" "import/./Frazey Ford/Indian Ocean/01 September Fields.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/09 Hold On My Heart 2.mp3" "import/./Genesis/We Can't Dance/09 Hold On My Heart 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/07 Tell Me Why 2.mp3" "import/./Genesis/We Can't Dance/07 Tell Me Why 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/03 Driving The Last Spike 2.mp3" "import/./Genesis/We Can't Dance/03 Driving The Last Spike 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/08 Living Forever 2.mp3" "import/./Genesis/We Can't Dance/08 Living Forever 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/05 Never A Time 2.mp3" "import/./Genesis/We Can't Dance/05 Never A Time 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/12 Fading Lights 2.mp3" "import/./Genesis/We Can't Dance/12 Fading Lights 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/10 Way Of The World 2.mp3" "import/./Genesis/We Can't Dance/10 Way Of The World 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/06 Dreaming While You Sleep 2.mp3" "import/./Genesis/We Can't Dance/06 Dreaming While You Sleep 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/02 Jesus He Knows Me 2.mp3" "import/./Genesis/We Can't Dance/02 Jesus He Knows Me 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/11 Since I Lost You 2.mp3" "import/./Genesis/We Can't Dance/11 Since I Lost You 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/01 No Son Of Mine 2.mp3" "import/./Genesis/We Can't Dance/01 No Son Of Mine 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Genesis/We Can't Dance/04 I Can't Dance 2.mp3" "import/./Genesis/We Can't Dance/04 I Can't Dance 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jackson Browne/Standing In the Breach/01 The Birds of St. Marks.m4a" "import/./Jackson Browne/Standing In the Breach/01 The Birds of St. Marks.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Phantogram/Mouthful of Diamonds/01 Mouthful Of Diamonds.m4a" "import/./Phantogram/Mouthful of Diamonds/01 Mouthful Of Diamonds.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Hunter Hunted/Hunter Hunted - EP/03 End of the World.m4a" "import/./Hunter Hunted/Hunter Hunted - EP/03 End of the World.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jack Johnson/From Here to Now to You/07 As I Was Saying.m4a" "import/./Jack Johnson/From Here to Now to You/07 As I Was Saying.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jack Johnson/Jack Johnson & Friends - Best of Kokua Festival (A Benefit for the Kokua Hawaii Foundation)/01 Better Together (Live).m4a" "import/./Jack Johnson/Jack Johnson & Friends - Best of Kokua Festival (A Benefit for the Kokua Hawaii Foundation)/01 Better Together (Live).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jack Johnson/Jack Johnson & Friends - Best of Kokua Festival (A Benefit for the Kokua Hawaii Foundation)/01 Better Together (Live) 1.m4a" "import/./Jack Johnson/Jack Johnson & Friends - Best of Kokua Festival (A Benefit for the Kokua Hawaii Foundation)/01 Better Together (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jack Johnson/At or With Me - Single/01 At or With Me.m4a" "import/./Jack Johnson/At or With Me - Single/01 At or With Me.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Yeah Yeah Yeahs/Mosquito/10 Despair.m4a" "import/./Yeah Yeah Yeahs/Mosquito/10 Despair.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Young the Giant/Mind Over Matter/04 Crystallized.m4a" "import/./Young the Giant/Mind Over Matter/04 Crystallized.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./P!nk/The Truth About Love/The Truth About Love - iTunes LP (v2.0).itlp/audio/Pink_TheTruthAboutLove_backgroundaudio.m4a" "import/./P!nk/The Truth About Love/The Truth About Love - iTunes LP (v2.0).itlp/audio/Pink_TheTruthAboutLove_backgroundaudio.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ha-Ash/Habitacion Doble/06 Already Home (With Brandi Carlile) 2.m4p" "import/./Ha-Ash/Habitacion Doble/06 Already Home (With Brandi Carlile) 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Janelle Monáe/The Electric Lady/09 Dance Apocalyptic.m4a" "import/./Janelle Monáe/The Electric Lady/09 Dance Apocalyptic.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Washed Out/Paracosm (Bonus Track Version)/02 It All Feels Right 1.m4a" "import/./Washed Out/Paracosm (Bonus Track Version)/02 It All Feels Right 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Washed Out/Paracosm (Bonus Track Version)/02 It All Feels Right.m4a" "import/./Washed Out/Paracosm (Bonus Track Version)/02 It All Feels Right.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Zee Avi/Zee Avi/10 Darling.m4a" "import/./Zee Avi/Zee Avi/10 Darling.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Peter Bjorn and John/Eyes - Single/01 Eyes.m4p" "import/./Peter Bjorn and John/Eyes - Single/01 Eyes.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Brett Dennen/Hope for the Hopeless/01 San Francisco.m4a" "import/./Brett Dennen/Hope for the Hopeless/01 San Francisco.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Triumph/Just a Game/07 Hold On.m4a" "import/./Triumph/Just a Game/07 Hold On.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Triumph/Allied Forces/09 Say Goodbye.m4a" "import/./Triumph/Allied Forces/09 Say Goodbye.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Triumph/Allied Forces/02 Magic Power.m4a" "import/./Triumph/Allied Forces/02 Magic Power.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Triumph/Allied Forces/06 Fight the Good Fight.m4a" "import/./Triumph/Allied Forces/06 Fight the Good Fight.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./BOY/Mutual Friends/04 Little Numbers 2.m4a" "import/./BOY/Mutual Friends/04 Little Numbers 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./BOY/Mutual Friends/04 Little Numbers.m4a" "import/./BOY/Mutual Friends/04 Little Numbers.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./BOY/Mutual Friends/04 Little Numbers 1.m4a" "import/./BOY/Mutual Friends/04 Little Numbers 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Clay Aiken/This Is the Night - Single/01 Bridge over Troubled Water.m4p" "import/./Clay Aiken/This Is the Night - Single/01 Bridge over Troubled Water.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Clay Aiken/This Is the Night - Single/01 Bridge over Troubled Water 2.m4p" "import/./Clay Aiken/This Is the Night - Single/01 Bridge over Troubled Water 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Clay Aiken/This Is the Night - Single/01 Bridge over Troubled Water 1.m4p" "import/./Clay Aiken/This Is the Night - Single/01 Bridge over Troubled Water 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jason Isbell/Something More Than Free/03 Flagship.m4a" "import/./Jason Isbell/Something More Than Free/03 Flagship.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Raphael Saadiq/100 Yard Dash - Single/01 100 Yard Dash 2.m4p" "import/./Raphael Saadiq/100 Yard Dash - Single/01 100 Yard Dash 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Death Cab for Cutie/Underneath the Sycamore - Single/01 Underneath the Sycamore.m4p" "import/./Death Cab for Cutie/Underneath the Sycamore - Single/01 Underneath the Sycamore.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Madeleine Peyroux/Standing On the Rooftop/02 The Kind You Can't Afford.m4a" "import/./Madeleine Peyroux/Standing On the Rooftop/02 The Kind You Can't Afford.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Madeleine Peyroux/Standing On the Rooftop/02 The Kind You Can't Afford 1.m4a" "import/./Madeleine Peyroux/Standing On the Rooftop/02 The Kind You Can't Afford 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Madeleine Peyroux/The Blue Room/02 Bye Bye Love.m4a" "import/./Madeleine Peyroux/The Blue Room/02 Bye Bye Love.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Madeleine Peyroux/The Blue Room/02 Bye Bye Love 1.m4a" "import/./Madeleine Peyroux/The Blue Room/02 Bye Bye Love 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Madeleine Peyroux/Bare Bones (Bonus Track Version)/01 Instead.m4a" "import/./Madeleine Peyroux/Bare Bones (Bonus Track Version)/01 Instead.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Mary J. Blige/A Mary Christmas/12 Noche De Paz (Silent Night) [feat. Marc Anthony].m4a" "import/./Mary J. Blige/A Mary Christmas/12 Noche De Paz (Silent Night) [feat. Marc Anthony].m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Mary J. Blige/The London Sessions/02 Doubt.m4a" "import/./Mary J. Blige/The London Sessions/02 Doubt.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bruno Mars/If I Knew - Single/01 If I Knew.m4p" "import/./Bruno Mars/If I Knew - Single/01 If I Knew.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bruno Mars/If I Knew - Single/01 If I Knew.m4a" "import/./Bruno Mars/If I Knew - Single/01 If I Knew.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Asleep At the Wheel/Still the King_ Celebrating the Music of Bob Wills and His Texas Playboys/03 The Girl I Left Behind Me (with The Avett Brothers).m4a" "import/./Asleep At the Wheel/Still the King_ Celebrating the Music of Bob Wills and His Texas Playboys/03 The Girl I Left Behind Me (with The Avett Brothers).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./HAIM/Days Are Gone/05 Honey & I.m4a" "import/./HAIM/Days Are Gone/05 Honey & I.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jenny O_/Automechanic/05 Learned My Lessons.m4a" "import/./Jenny O_/Automechanic/05 Learned My Lessons.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jenny O_/Automechanic/05 Learned My Lessons 1.m4a" "import/./Jenny O_/Automechanic/05 Learned My Lessons 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Tough Alliance/A New Chance/07 Neo Violence 2.m4p" "import/./The Tough Alliance/A New Chance/07 Neo Violence 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Charlotte Gainsbourg/IRM/05 Heaven Çan Wait 1.m4a" "import/./Charlotte Gainsbourg/IRM/05 Heaven Çan Wait 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Charlotte Gainsbourg/IRM/05 Heaven Çan Wait.m4a" "import/./Charlotte Gainsbourg/IRM/05 Heaven Çan Wait.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Hamilton Leithauser/Black Hours (Deluxe Edition)/08 I Don't Need Anyone.m4a" "import/./Hamilton Leithauser/Black Hours (Deluxe Edition)/08 I Don't Need Anyone.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cold Specks/I Predict a Graceful Expulsion/04 When the City Lights Dim 2.m4a" "import/./Cold Specks/I Predict a Graceful Expulsion/04 When the City Lights Dim 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cold Specks/I Predict a Graceful Expulsion/04 When the City Lights Dim.m4a" "import/./Cold Specks/I Predict a Graceful Expulsion/04 When the City Lights Dim.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cold Specks/I Predict a Graceful Expulsion/04 When the City Lights Dim 1.m4a" "import/./Cold Specks/I Predict a Graceful Expulsion/04 When the City Lights Dim 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bryan Adams/Waking Up The Neighbours/01 Is Your Mama Gonna Miss Ya_ 2.mp3" "import/./Bryan Adams/Waking Up The Neighbours/01 Is Your Mama Gonna Miss Ya_ 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bryan Adams/Waking Up The Neighbours/12 (Everything I Do) I Do It For You 2.mp3" "import/./Bryan Adams/Waking Up The Neighbours/12 (Everything I Do) I Do It For You 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Eric Uglum/Shenandoah Wind/02 Shenandoah Wind 4.m4p" "import/./Eric Uglum/Shenandoah Wind/02 Shenandoah Wind 4.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Eric Uglum/Shenandoah Wind/02 Shenandoah Wind 2.m4p" "import/./Eric Uglum/Shenandoah Wind/02 Shenandoah Wind 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Eric Uglum/Shenandoah Wind/02 Shenandoah Wind 3.m4p" "import/./Eric Uglum/Shenandoah Wind/02 Shenandoah Wind 3.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sarah Jarosz/Build Me Up From Bones/01 Over the Edge.m4a" "import/./Sarah Jarosz/Build Me Up From Bones/01 Over the Edge.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/01 Rebels 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/01 Rebels 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/05 Make It Better (Forget About Me) 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/05 Make It Better (Forget About Me) 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/02 It Ain't Nothin' To Me 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/02 It Ain't Nothin' To Me 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/04 Southern Accents 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/04 Southern Accents 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/03 Don't Come Around Here No More 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/03 Don't Come Around Here No More 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/06 Spike 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/06 Spike 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tom Petty & The Heartbreakers/Southern Accents/08 Mary's New Car 2.mp3" "import/./Tom Petty & The Heartbreakers/Southern Accents/08 Mary's New Car 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Feist/Bittersweet Melodies - Single/01 Bittersweet Melodies.m4a" "import/./Feist/Bittersweet Melodies - Single/01 Bittersweet Melodies.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Feist/Bittersweet Melodies - Single/01 Bittersweet Melodies 1.m4a" "import/./Feist/Bittersweet Melodies - Single/01 Bittersweet Melodies 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Demo/Unknown Album/Metal.mp3" "import/./Demo/Unknown Album/Metal.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Alabama Shakes/Sound & Color/02 Don't Wanna Fight.m4a" "import/./Alabama Shakes/Sound & Color/02 Don't Wanna Fight.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-03 You Really Got Me.mp3" "import/./Van Halen/Van Halen/1-03 You Really Got Me.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-06 Jamie's Cryin'.mp3" "import/./Van Halen/Van Halen/1-06 Jamie's Cryin'.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-02 Eruption.mp3" "import/./Van Halen/Van Halen/1-02 Eruption.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-10 Ice Cream Man.mp3" "import/./Van Halen/Van Halen/1-10 Ice Cream Man.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-04 Ain't Talkin' 'Bout Love.mp3" "import/./Van Halen/Van Halen/1-04 Ain't Talkin' 'Bout Love.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-09 Little Dreamer.mp3" "import/./Van Halen/Van Halen/1-09 Little Dreamer.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-08 Feel Your Love Tonight.mp3" "import/./Van Halen/Van Halen/1-08 Feel Your Love Tonight.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-01 Runnin' With The Devil.mp3" "import/./Van Halen/Van Halen/1-01 Runnin' With The Devil.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-07 Atomic Punk.mp3" "import/./Van Halen/Van Halen/1-07 Atomic Punk.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-11 On Fire.mp3" "import/./Van Halen/Van Halen/1-11 On Fire.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Van Halen/1-05 I'm The One.mp3" "import/./Van Halen/Van Halen/1-05 I'm The One.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-07 Take Your Whiskey Home.mp3" "import/./Van Halen/Women and Children First/1-07 Take Your Whiskey Home.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-03 Fools.mp3" "import/./Van Halen/Women and Children First/1-03 Fools.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-04 Romeo Delight.mp3" "import/./Van Halen/Women and Children First/1-04 Romeo Delight.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-08 Could This Be Magic_.mp3" "import/./Van Halen/Women and Children First/1-08 Could This Be Magic_.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-01 And The Cradle Will Rock....mp3" "import/./Van Halen/Women and Children First/1-01 And The Cradle Will Rock....mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-05 Tora! Tora!.mp3" "import/./Van Halen/Women and Children First/1-05 Tora! Tora!.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-06 Loss Of Control.mp3" "import/./Van Halen/Women and Children First/1-06 Loss Of Control.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-02 Everybody Wants Some!!.mp3" "import/./Van Halen/Women and Children First/1-02 Everybody Wants Some!!.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Women and Children First/1-09 In A Simple Rhyme.mp3" "import/./Van Halen/Women and Children First/1-09 In A Simple Rhyme.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/01 Mean Street.mp3" "import/./Van Halen/Fair Warning/01 Mean Street.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/07 So This Is Love_.mp3" "import/./Van Halen/Fair Warning/07 So This Is Love_.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/02 _Dirty Movies_.mp3" "import/./Van Halen/Fair Warning/02 _Dirty Movies_.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/06 Push Comes to Shove.mp3" "import/./Van Halen/Fair Warning/06 Push Comes to Shove.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/09 One Foot out the Door.mp3" "import/./Van Halen/Fair Warning/09 One Foot out the Door.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/08 Sunday Afternoon in the Park.mp3" "import/./Van Halen/Fair Warning/08 Sunday Afternoon in the Park.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/04 Hear About It Later.mp3" "import/./Van Halen/Fair Warning/04 Hear About It Later.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/03 Sinner's Swing!.mp3" "import/./Van Halen/Fair Warning/03 Sinner's Swing!.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Halen/Fair Warning/05 Unchained.mp3" "import/./Van Halen/Fair Warning/05 Unchained.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Diana Krall/The Boy from Ipanema - Single/01 The Boy from Ipanema.m4p" "import/./Diana Krall/The Boy from Ipanema - Single/01 The Boy from Ipanema.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Justin Timberlake/The 20_20 Experience/04 Strawberry Bubblegum 1.m4a" "import/./Justin Timberlake/The 20_20 Experience/04 Strawberry Bubblegum 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Justin Timberlake/The 20_20 Experience/04 Strawberry Bubblegum.m4a" "import/./Justin Timberlake/The 20_20 Experience/04 Strawberry Bubblegum.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Broken Bells/After the Disco/02 After the Disco.m4a" "import/./Broken Bells/After the Disco/02 After the Disco.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Parts & Labor/Constant Future/05 Rest.m4a" "import/./Parts & Labor/Constant Future/05 Rest.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Jenny Lewis/The Voyager/03 Just One of the Guys.m4a" "import/./Jenny Lewis/The Voyager/03 Just One of the Guys.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Kate Earl/Stronger/02 One Woman Army.m4a" "import/./Kate Earl/Stronger/02 One Woman Army.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Kate Earl/Stronger/02 One Woman Army 1.m4a" "import/./Kate Earl/Stronger/02 One Woman Army 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Gary Go/Wonderful (Radio Edit) - Single/01 Wonderful (Radio Edit).m4a" "import/./Gary Go/Wonderful (Radio Edit) - Single/01 Wonderful (Radio Edit).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Daniel Isaiah/High Twilight/02 High Twilight 1.m4a" "import/./Daniel Isaiah/High Twilight/02 High Twilight 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Daniel Isaiah/High Twilight/02 High Twilight.m4a" "import/./Daniel Isaiah/High Twilight/02 High Twilight.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Watson Twins/Modern Man + Devil In You - Single/01 Modern Man.m4a" "import/./The Watson Twins/Modern Man + Devil In You - Single/01 Modern Man.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Nickle Creek-Chris Thile/Stealing Second/07 Leaves Fall 2.mp3" "import/./Nickle Creek-Chris Thile/Stealing Second/07 Leaves Fall 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Booker T. Jones/Just a Friend [feat. Biz Markie, Matt Berninger, and Sharon Jones] - Single/01 Just a Friend (feat. Biz Markie, Matt Berninger, and Sharon Jones)(Bonus track).m4p" "import/./Booker T. Jones/Just a Friend [feat. Biz Markie, Matt Berninger, and Sharon Jones] - Single/01 Just a Friend (feat. Biz Markie, Matt Berninger, and Sharon Jones)(Bonus track).m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Lake Street Dive/Bad Self Portraits/05 You Go Down Smooth.m4a" "import/./Lake Street Dive/Bad Self Portraits/05 You Go Down Smooth.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Mariachi El Bronx/Mariachi El Bronx (III)/02 Wildfires.m4a" "import/./Mariachi El Bronx/Mariachi El Bronx (III)/02 Wildfires.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Edward Sharpe & The Magnetic Zeros/Man On Fire - Single/01 Man On Fire 1.m4a" "import/./Edward Sharpe & The Magnetic Zeros/Man On Fire - Single/01 Man On Fire 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Edward Sharpe & The Magnetic Zeros/Man On Fire - Single/01 Man On Fire.m4a" "import/./Edward Sharpe & The Magnetic Zeros/Man On Fire - Single/01 Man On Fire.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Yuna/Nocturnal (Deluxe Edition)/03 Rescue.m4a" "import/./Yuna/Nocturnal (Deluxe Edition)/03 Rescue.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Depeche Mode/Delta Machine (Deluxe Version)/03 Heaven 1.m4a" "import/./Depeche Mode/Delta Machine (Deluxe Version)/03 Heaven 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Depeche Mode/Delta Machine (Deluxe Version)/03 Heaven.m4a" "import/./Depeche Mode/Delta Machine (Deluxe Version)/03 Heaven.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Lanu/Beautiful Trash (feat. Megan Washington) - EP/01 Beautiful Trash (feat. Megan Washington).m4a" "import/./Lanu/Beautiful Trash (feat. Megan Washington) - EP/01 Beautiful Trash (feat. Megan Washington).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/08 Wayfaring Stranger 2.mp3" "import/./Sharon Isbin/Journey to the New World/08 Wayfaring Stranger 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/18 Strings & Threads Suite_II. Sailor's Jig 2.mp3" "import/./Sharon Isbin/Journey to the New World/18 Strings & Threads Suite_II. Sailor's Jig 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/03 La Rossignol 2.mp3" "import/./Sharon Isbin/Journey to the New World/03 La Rossignol 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/06 Wild Mountain Thyme 2.mp3" "import/./Sharon Isbin/Journey to the New World/06 Wild Mountain Thyme 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/05 The Drunken Sailor 2.mp3" "import/./Sharon Isbin/Journey to the New World/05 The Drunken Sailor 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/04 Greensleeves 2.mp3" "import/./Sharon Isbin/Journey to the New World/04 Greensleeves 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/26 Strings & Threads Suite_X. Queen of the Cumberland 2.mp3" "import/./Sharon Isbin/Journey to the New World/26 Strings & Threads Suite_X. Queen of the Cumberland 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/14 Joan Baez Suite, Opus 144_VI. Where have all the Flowers Gone_ 2.mp3" "import/./Sharon Isbin/Journey to the New World/14 Joan Baez Suite, Opus 144_VI. Where have all the Flowers Gone_ 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/28 Strings & Threads Suite_XII. Swing 2.mp3" "import/./Sharon Isbin/Journey to the New World/28 Strings & Threads Suite_XII. Swing 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/22 Strings & Threads Suite_VI. Road to Appalachia 2.mp3" "import/./Sharon Isbin/Journey to the New World/22 Strings & Threads Suite_VI. Road to Appalachia 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/02 Lord Willoughby's Welcome Home 2.mp3" "import/./Sharon Isbin/Journey to the New World/02 Lord Willoughby's Welcome Home 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/12 Joan Baez Suite, Opus 144_IV. The Unquiet Grave 2.mp3" "import/./Sharon Isbin/Journey to the New World/12 Joan Baez Suite, Opus 144_IV. The Unquiet Grave 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/10 Joan Baez Suite, Opus 144_II. The House of the Rising Sun 2.mp3" "import/./Sharon Isbin/Journey to the New World/10 Joan Baez Suite, Opus 144_II. The House of the Rising Sun 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/15 Joan Baez Suite, Opus 144_VII. Finale_ Rake and Rambling Boy; Wildwood Flower; The Trees they do Grow High 2.mp3" "import/./Sharon Isbin/Journey to the New World/15 Joan Baez Suite, Opus 144_VII. Finale_ Rake and Rambling Boy; Wildwood Flower; The Trees they do Grow High 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/17 Strings & Threads Suite_I. Fair Dancer Reel 2.mp3" "import/./Sharon Isbin/Journey to the New World/17 Strings & Threads Suite_I. Fair Dancer Reel 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/09 Joan Baez Suite, Opus 144_I. Fantasia_ Once I had a Sweetheart; Rambler Gambler; Barbara Allen 2.mp3" "import/./Sharon Isbin/Journey to the New World/09 Joan Baez Suite, Opus 144_I. Fantasia_ Once I had a Sweetheart; Rambler Gambler; Barbara Allen 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/01 Mr. Drewry's Accords 2.mp3" "import/./Sharon Isbin/Journey to the New World/01 Mr. Drewry's Accords 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/16 Go 'Way From My Window 2.mp3" "import/./Sharon Isbin/Journey to the New World/16 Go 'Way From My Window 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/24 Strings & Threads Suite_VIII. Cotton Pickin' Blues 2.mp3" "import/./Sharon Isbin/Journey to the New World/24 Strings & Threads Suite_VIII. Cotton Pickin' Blues 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/21 Strings & Threads Suite_V. Pilgrim's Waltz 2.mp3" "import/./Sharon Isbin/Journey to the New World/21 Strings & Threads Suite_V. Pilgrim's Waltz 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/27 Strings & Threads Suite_XI. Texas Dance Hall Blues 2.mp3" "import/./Sharon Isbin/Journey to the New World/27 Strings & Threads Suite_XI. Texas Dance Hall Blues 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/13 Joan Baez Suite, Opus 144_V. Silkie 2.mp3" "import/./Sharon Isbin/Journey to the New World/13 Joan Baez Suite, Opus 144_V. Silkie 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/07 Andecy 2.mp3" "import/./Sharon Isbin/Journey to the New World/07 Andecy 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/25 Strings & Threads Suite_IX. Pickin' Parlor Rag 2.mp3" "import/./Sharon Isbin/Journey to the New World/25 Strings & Threads Suite_IX. Pickin' Parlor Rag 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/23 Strings & Threads Suite_VII. Shine On 2.mp3" "import/./Sharon Isbin/Journey to the New World/23 Strings & Threads Suite_VII. Shine On 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/29 Strings & Threads Suite_XIII. Sweet Suzanne 2.mp3" "import/./Sharon Isbin/Journey to the New World/29 Strings & Threads Suite_XIII. Sweet Suzanne 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/20 Strings & Threads Suite_IV. Off to Sea 2.mp3" "import/./Sharon Isbin/Journey to the New World/20 Strings & Threads Suite_IV. Off to Sea 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/11 Joan Baez Suite, Opus 144_III. The Lily of the West 2.mp3" "import/./Sharon Isbin/Journey to the New World/11 Joan Baez Suite, Opus 144_III. The Lily of the West 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Isbin/Journey to the New World/19 Strings & Threads Suite_III. Captain's Jig 2.mp3" "import/./Sharon Isbin/Journey to the New World/19 Strings & Threads Suite_III. Captain's Jig 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sharon Jones & The Dap-Kings/Give the People What They Want (Deluxe Version)/02 Stranger to My Happiness.m4a" "import/./Sharon Jones & The Dap-Kings/Give the People What They Want (Deluxe Version)/02 Stranger to My Happiness.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dawes/All Your Favorite Bands/01 Things Happen.m4a" "import/./Dawes/All Your Favorite Bands/01 Things Happen.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./U2/Songs of Innocence/09 Sleep Like a Baby Tonight.m4a" "import/./U2/Songs of Innocence/09 Sleep Like a Baby Tonight.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./U2/Songs of Innocence/08 Cedarwood Road.m4a" "import/./U2/Songs of Innocence/08 Cedarwood Road.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Andrea Bocelli/Silent Night - Single/01 Silent Night.m4a" "import/./Andrea Bocelli/Silent Night - Single/01 Silent Night.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bahamas/Bahamas is Afie/04 All the Time.m4a" "import/./Bahamas/Bahamas is Afie/04 All the Time.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Emma Louise/Boy - Single/01 Boy.m4a" "import/./Emma Louise/Boy - Single/01 Boy.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Joey Alexander/My Favorite Things (Deluxe Edition)/05 Ma Blues.m4a" "import/./Joey Alexander/My Favorite Things (Deluxe Edition)/05 Ma Blues.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Caravan - Single/01 Caravan (Single Version).m4a" "import/./Rush/Caravan - Single/01 Caravan (Single Version).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Caravan - Single/02 BU2B (Single Version).m4a" "import/./Rush/Caravan - Single/02 BU2B (Single Version).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/03 Red Sector A 1.m4p" "import/./Rush/Grace Under Pressure/03 Red Sector A 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/07 Red Lenses 1.m4p" "import/./Rush/Grace Under Pressure/07 Red Lenses 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/01 Distant Early Warning 2.m4p" "import/./Rush/Grace Under Pressure/01 Distant Early Warning 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/02 Afterimage 1.m4p" "import/./Rush/Grace Under Pressure/02 Afterimage 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/06 Kid Gloves 1.m4p" "import/./Rush/Grace Under Pressure/06 Kid Gloves 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/04 The Enemy Within, Pt. 1 of _Fear_ 1.m4p" "import/./Rush/Grace Under Pressure/04 The Enemy Within, Pt. 1 of _Fear_ 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/04 The Enemy Within, Pt. 1 of _Fear_ 2.m4p" "import/./Rush/Grace Under Pressure/04 The Enemy Within, Pt. 1 of _Fear_ 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/07 Red Lenses 2.m4p" "import/./Rush/Grace Under Pressure/07 Red Lenses 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/03 Red Sector A 2.m4p" "import/./Rush/Grace Under Pressure/03 Red Sector A 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/08 Between the Wheels 2.m4p" "import/./Rush/Grace Under Pressure/08 Between the Wheels 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/02 Afterimage 2.m4p" "import/./Rush/Grace Under Pressure/02 Afterimage 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/06 Kid Gloves 2.m4p" "import/./Rush/Grace Under Pressure/06 Kid Gloves 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rush/Grace Under Pressure/05 The Body Electric 2.m4p" "import/./Rush/Grace Under Pressure/05 The Body Electric 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Benjamin Booker/Benjamin Booker/01 Violent Shiver.m4a" "import/./Benjamin Booker/Benjamin Booker/01 Violent Shiver.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Basia Bulat/Heart of My Own (Bonus Track Version)/05 Heart of My Own.m4a" "import/./Basia Bulat/Heart of My Own (Bonus Track Version)/05 Heart of My Own.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Cookers/Time and Time Again/05 Farewell Mulgrew.m4a" "import/./The Cookers/Time and Time Again/05 Farewell Mulgrew.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rufus Wainwright/Sometimes You Need - Single/01 Sometimes You Need 1.m4a" "import/./Rufus Wainwright/Sometimes You Need - Single/01 Sometimes You Need 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Rufus Wainwright/Sometimes You Need - Single/01 Sometimes You Need.m4a" "import/./Rufus Wainwright/Sometimes You Need - Single/01 Sometimes You Need.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Who/Who Are You/04 Sister Disco 2.mp3" "import/./The Who/Who Are You/04 Sister Disco 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Who/Who Are You/03 905 2.mp3" "import/./The Who/Who Are You/03 905 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Who/Who Are You/01 New Song 2.mp3" "import/./The Who/Who Are You/01 New Song 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Who/Who Are You/02 Had Enough 2.mp3" "import/./The Who/Who Are You/02 Had Enough 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Algebra Blessett/Recovery/03 Right Next To You.m4a" "import/./Algebra Blessett/Recovery/03 Right Next To You.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dave Matthews Band/Write a Song - Single/01 Write a Song.m4p" "import/./Dave Matthews Band/Write a Song - Single/01 Write a Song.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dave Matthews Band/If Only - Single/01 If Only 3.m4a" "import/./Dave Matthews Band/If Only - Single/01 If Only 3.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dave Matthews Band/If Only - Single/01 If Only 1.m4a" "import/./Dave Matthews Band/If Only - Single/01 If Only 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dave Matthews Band/If Only - Single/01 If Only.m4a" "import/./Dave Matthews Band/If Only - Single/01 If Only.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Dave Matthews Band/If Only - Single/01 If Only 4.m4a" "import/./Dave Matthews Band/If Only - Single/01 If Only 4.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Monsters of Folk/Monsters of Folk/06 Baby Boomer.m4a" "import/./Monsters of Folk/Monsters of Folk/06 Baby Boomer.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Phosphorescent/Muchacho/03 Ride On _ Right On 1.m4a" "import/./Phosphorescent/Muchacho/03 Ride On _ Right On 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Phosphorescent/Muchacho/03 Ride On _ Right On.m4a" "import/./Phosphorescent/Muchacho/03 Ride On _ Right On.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Playing for Change/Playing For Change 3_ Songs Around the World/04 Down By the Riverside (feat. Keb' Mo', Preservation Hall Jazz Band & Grandpa Elliott).m4a" "import/./Playing for Change/Playing For Change 3_ Songs Around the World/04 Down By the Riverside (feat. Keb' Mo', Preservation Hall Jazz Band & Grandpa Elliott).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Eric Clapton/Rush/10 Tears In Heaven 2.mp3" "import/./Eric Clapton/Rush/10 Tears In Heaven 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Eric Clapton/The Breeze_ An Appreciation of JJ Cale/01 Call Me the Breeze.m4a" "import/./Eric Clapton/The Breeze_ An Appreciation of JJ Cale/01 Call Me the Breeze.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Eric Clapton/Old Sock/02 Angel 1.m4a" "import/./Eric Clapton/Old Sock/02 Angel 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tegan and Sara/Heartthrob (Deluxe Version)/01 Closer 2.m4a" "import/./Tegan and Sara/Heartthrob (Deluxe Version)/01 Closer 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tegan and Sara/Heartthrob (Deluxe Version)/01 Closer.m4a" "import/./Tegan and Sara/Heartthrob (Deluxe Version)/01 Closer.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Tegan and Sara/Heartthrob (Deluxe Version)/01 Closer 1.m4a" "import/./Tegan and Sara/Heartthrob (Deluxe Version)/01 Closer 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bonnie Raitt/Down to You - Single/01 Down to You.m4a" "import/./Bonnie Raitt/Down to You - Single/01 Down to You.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bonnie Raitt/Down to You - Single/01 Down to You 1.m4a" "import/./Bonnie Raitt/Down to You - Single/01 Down to You 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./She & Him/Volume 3/02 Never Wanted Your Love.m4a" "import/./She & Him/Volume 3/02 Never Wanted Your Love.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./She & Him/Classics/04 Stay Awhile.m4a" "import/./She & Him/Classics/04 Stay Awhile.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./She & Him/A Very She & Him Christmas/04 I'll Be Home for Christmas.m4a" "import/./She & Him/A Very She & Him Christmas/04 I'll Be Home for Christmas.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./She & Him/A Very She & Him Christmas/04 I'll Be Home for Christmas 1.m4a" "import/./She & Him/A Very She & Him Christmas/04 I'll Be Home for Christmas 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Chris Thile, Edgar Meyer, Stuart Duncan & Yo-Yo Ma/Attaboy - Single/01 Attaboy 1.m4a" "import/./Chris Thile, Edgar Meyer, Stuart Duncan & Yo-Yo Ma/Attaboy - Single/01 Attaboy 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Chris Thile, Edgar Meyer, Stuart Duncan & Yo-Yo Ma/Attaboy - Single/01 Attaboy.m4a" "import/./Chris Thile, Edgar Meyer, Stuart Duncan & Yo-Yo Ma/Attaboy - Single/01 Attaboy.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./R.E.M_/ÜBerlin - Single/01 ÜBerlin.m4a" "import/./R.E.M_/ÜBerlin - Single/01 ÜBerlin.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Mavis Staples/One True Vine/05 Far Celestial Shore 1.m4a" "import/./Mavis Staples/One True Vine/05 Far Celestial Shore 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Mavis Staples/One True Vine/05 Far Celestial Shore.m4a" "import/./Mavis Staples/One True Vine/05 Far Celestial Shore.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Yo-Yo Ma, Stuart Duncan, Chris Thile, Edgar Meyer & Aoife O'Donovan/Here and Heaven - Single/01 Here and Heaven 1.m4a" "import/./Yo-Yo Ma, Stuart Duncan, Chris Thile, Edgar Meyer & Aoife O'Donovan/Here and Heaven - Single/01 Here and Heaven 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Yo-Yo Ma, Stuart Duncan, Chris Thile, Edgar Meyer & Aoife O'Donovan/Here and Heaven - Single/01 Here and Heaven.m4a" "import/./Yo-Yo Ma, Stuart Duncan, Chris Thile, Edgar Meyer & Aoife O'Donovan/Here and Heaven - Single/01 Here and Heaven.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sarah McLachlan/Afterglow/01 Fallen 1.m4p" "import/./Sarah McLachlan/Afterglow/01 Fallen 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sarah McLachlan/Afterglow/01 Fallen 2.m4p" "import/./Sarah McLachlan/Afterglow/01 Fallen 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sarah McLachlan/Afterglow/01 Fallen 2.mp3" "import/./Sarah McLachlan/Afterglow/01 Fallen 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sarah McLachlan/Shine On (Deluxe Edition)/01 In Your Shoes.m4a" "import/./Sarah McLachlan/Shine On (Deluxe Edition)/01 In Your Shoes.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Morrison/Born to Sing_ No Plan B/04 End of the Rainbow 1.m4a" "import/./Van Morrison/Born to Sing_ No Plan B/04 End of the Rainbow 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Van Morrison/Born to Sing_ No Plan B/04 End of the Rainbow.m4a" "import/./Van Morrison/Born to Sing_ No Plan B/04 End of the Rainbow.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Brazos/Saltwater/03 How the Ranks Was Won 1.m4a" "import/./Brazos/Saltwater/03 How the Ranks Was Won 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Brazos/Saltwater/03 How the Ranks Was Won.m4a" "import/./Brazos/Saltwater/03 How the Ranks Was Won.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cayucas/Bigfoot/01 Cayucos 1.m4a" "import/./Cayucas/Bigfoot/01 Cayucos 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cayucas/Bigfoot/01 Cayucos.m4a" "import/./Cayucas/Bigfoot/01 Cayucos.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Punch Brothers/The Phosphorescent Blues/04 I Blew It Off.m4a" "import/./Punch Brothers/The Phosphorescent Blues/04 I Blew It Off.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./We Are Augustines/Chapel Song - Single/01 Chapel Song.m4p" "import/./We Are Augustines/Chapel Song - Single/01 Chapel Song.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Leela James/Tell Me You Love Me - Single/01 Tell Me You Love Me.m4a" "import/./Leela James/Tell Me You Love Me - Single/01 Tell Me You Love Me.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./PHOX/PHOX/03 Slow Motion.m4a" "import/./PHOX/PHOX/03 Slow Motion.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cold War Kids/Mine Is Yours (Deluxe Version)/06 Skip the Charades.m4a" "import/./Cold War Kids/Mine Is Yours (Deluxe Version)/06 Skip the Charades.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Miles Davis Quintet/Workin' With the Miles Davis Quintet (Remastered)/02 Four.m4a" "import/./Miles Davis Quintet/Workin' With the Miles Davis Quintet (Remastered)/02 Four.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Miles Davis Quintet/Workin' (RVG Remaster)/02 Four.m4a" "import/./Miles Davis Quintet/Workin' (RVG Remaster)/02 Four.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/03 Intro (Live) 2.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/03 Intro (Live) 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/08 Arlington (Live) 1.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/08 Arlington (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/13 Intro (Live) 1.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/13 Intro (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/06 Intro (Live) 2.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/06 Intro (Live) 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/17 Intro (Live) 2.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/17 Intro (Live) 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/02 Summertime (Live).m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/02 Summertime (Live).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/13 Intro (Live) 2.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/13 Intro (Live) 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/06 Intro (Live) 1.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/06 Intro (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/09 Bring Me Li'l Water Silvy (Live) 1.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/09 Bring Me Li'l Water Silvy (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/17 Intro (Live) 1.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/17 Intro (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/03 Intro (Live) 1.m4a" "import/./The Wailin' Jennys/Live at The Mauch Chunk Opera House/03 Intro (Live) 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Cave Singers/Naomi/12 When the World 1.m4a" "import/./The Cave Singers/Naomi/12 When the World 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Cave Singers/Naomi/12 When the World 2.m4a" "import/./The Cave Singers/Naomi/12 When the World 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Cave Singers/Naomi/12 When the World.m4a" "import/./The Cave Singers/Naomi/12 When the World.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Various Artists/iTunes Holiday Sampler/iTunes Holiday Sampler - iTunes LP (v3.0).itlp/audio/intro.m4a" "import/./Various Artists/iTunes Holiday Sampler/iTunes Holiday Sampler - iTunes LP (v3.0).itlp/audio/intro.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Sheryl Crow/Feels Like Home/03 Give It To Me.m4a" "import/./Sheryl Crow/Feels Like Home/03 Give It To Me.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Zac Brown Band/The Wind - Single/01 The Wind 1.m4a" "import/./Zac Brown Band/The Wind - Single/01 The Wind 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Zac Brown Band/The Wind - Single/01 The Wind.m4a" "import/./Zac Brown Band/The Wind - Single/01 The Wind.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Junior Boys/Begone Dull Care/04 Dull to Pause.m4a" "import/./Junior Boys/Begone Dull Care/04 Dull to Pause.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Queen/Queen_ Greatest Hits/02 We Are the Champions 2.m4p" "import/./Queen/Queen_ Greatest Hits/02 We Are the Champions 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Queen/Queen_ Greatest Hits/02 We Are the Champions 1.m4p" "import/./Queen/Queen_ Greatest Hits/02 We Are the Champions 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Queen/Queen_ Greatest Hits/01 We Will Rock You 2.m4p" "import/./Queen/Queen_ Greatest Hits/01 We Will Rock You 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Queen/Queen_ Greatest Hits/01 We Will Rock You 1.m4p" "import/./Queen/Queen_ Greatest Hits/01 We Will Rock You 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Meshell Ndegeocello/Devil's Halo/02 Tie One On.m4a" "import/./Meshell Ndegeocello/Devil's Halo/02 Tie One On.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/It Came Upon a Midnight Clear - Single/01 It Came Upon a Midnight Clear 1.m4a" "import/./Norah Jones/It Came Upon a Midnight Clear - Single/01 It Came Upon a Midnight Clear 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/It Came Upon a Midnight Clear - Single/01 It Came Upon a Midnight Clear.m4a" "import/./Norah Jones/It Came Upon a Midnight Clear - Single/01 It Came Upon a Midnight Clear.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/02 What Am I To You_ 2.mp3" "import/./Norah Jones/Feels Like Home/02 What Am I To You_ 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/08 Toes 2.mp3" "import/./Norah Jones/Feels Like Home/08 Toes 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/12 The Prettiest Thing 2.mp3" "import/./Norah Jones/Feels Like Home/12 The Prettiest Thing 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/01 Sunrise 2.mp3" "import/./Norah Jones/Feels Like Home/01 Sunrise 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/09 Humble Me 2.mp3" "import/./Norah Jones/Feels Like Home/09 Humble Me 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/05 In The Morning 2.mp3" "import/./Norah Jones/Feels Like Home/05 In The Morning 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/11 The Long Way Home 2.mp3" "import/./Norah Jones/Feels Like Home/11 The Long Way Home 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/03 Those Sweet Words 2.mp3" "import/./Norah Jones/Feels Like Home/03 Those Sweet Words 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Norah Jones/Feels Like Home/13 Don't Miss You At All 2.mp3" "import/./Norah Jones/Feels Like Home/13 Don't Miss You At All 2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Taylor Swift/This Love - Single/01 This Love.m4a" "import/./Taylor Swift/This Love - Single/01 This Love.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ivan & Alyosha/Easy to Love - Single/01 Easy To Love.m4a" "import/./Ivan & Alyosha/Easy to Love - Single/01 Easy To Love.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ivan & Alyosha/Easy to Love - Single/01 Easy To Love 2.m4a" "import/./Ivan & Alyosha/Easy to Love - Single/01 Easy To Love 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ivan & Alyosha/Easy to Love - Single/01 Easy To Love 1.m4a" "import/./Ivan & Alyosha/Easy to Love - Single/01 Easy To Love 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Leonard Cohen/Banjo - Single/01 Banjo 1.m4a" "import/./Leonard Cohen/Banjo - Single/01 Banjo 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Leonard Cohen/Banjo - Single/01 Banjo.m4a" "import/./Leonard Cohen/Banjo - Single/01 Banjo.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Beck/Morning Phase/05 Blue Moon.m4a" "import/./Beck/Morning Phase/05 Blue Moon.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./JD McPherson/Twinkle (Little Christmas Lights) - Single/01 Twinkle (Little Christmas Lights).m4a" "import/./JD McPherson/Twinkle (Little Christmas Lights) - Single/01 Twinkle (Little Christmas Lights).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bobby Womack/The Bravest Man in the Universe/01 The Bravest Man in the Universe 1.m4a" "import/./Bobby Womack/The Bravest Man in the Universe/01 The Bravest Man in the Universe 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Bobby Womack/The Bravest Man in the Universe/01 The Bravest Man in the Universe.m4a" "import/./Bobby Womack/The Bravest Man in the Universe/01 The Bravest Man in the Universe.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Wye Oak/We Were Wealth - Single/01 We Were Wealth.m4a" "import/./Wye Oak/We Were Wealth - Single/01 We Were Wealth.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Wye Oak/We Were Wealth/01 We Were Wealth 3.m4a" "import/./Wye Oak/We Were Wealth/01 We Were Wealth 3.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Laurent Korcia/Laurent Korcia_ Cinema/01 Cinema Paradiso.m4a" "import/./Laurent Korcia/Laurent Korcia_ Cinema/01 Cinema Paradiso.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Holcombe Waller/Into the Dark Unknown/05 Hardliners 1.m4a" "import/./Holcombe Waller/Into the Dark Unknown/05 Hardliners 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Holcombe Waller/Into the Dark Unknown/05 Hardliners.m4a" "import/./Holcombe Waller/Into the Dark Unknown/05 Hardliners.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Benjamin Gibbard/Former Lives/03 Teardrop Windows 1.m4a" "import/./Benjamin Gibbard/Former Lives/03 Teardrop Windows 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Benjamin Gibbard/Former Lives/03 Teardrop Windows.m4a" "import/./Benjamin Gibbard/Former Lives/03 Teardrop Windows.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./k.d. lang and the Siss Boom Bang/A Sleep With No Dreaming - Single/01 A Sleep with No Dreaming.m4a" "import/./k.d. lang and the Siss Boom Bang/A Sleep With No Dreaming - Single/01 A Sleep with No Dreaming.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Geoffrey Gurrumul Yunupingu/Wiyathul - Single/01 Wiyathul.m4a" "import/./Geoffrey Gurrumul Yunupingu/Wiyathul - Single/01 Wiyathul.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./John Mellencamp/Words & Music - John Mellencamp's Greatest Hits/2-13 Jack & Diane 2.m4p" "import/./John Mellencamp/Words & Music - John Mellencamp's Greatest Hits/2-13 Jack & Diane 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Telekinesis/12 Desperate Straight Lines/10 Country Lane.m4a" "import/./Telekinesis/12 Desperate Straight Lines/10 Country Lane.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ray Charles/Genius Loves Company (10th Anniversary Edition)/01 Here We Go Again.m4a" "import/./Ray Charles/Genius Loves Company (10th Anniversary Edition)/01 Here We Go Again.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-05 Hit Single.m4a" "import/./Heart/The Essential 3.0/3-05 Hit Single.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-02 Dream Of The Archer.m4a" "import/./Heart/The Essential 3.0/3-02 Dream Of The Archer.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-04 Mistral Wind (Live).m4a" "import/./Heart/The Essential 3.0/3-04 Mistral Wind (Live).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-03 Bebe Le Strange.m4a" "import/./Heart/The Essential 3.0/3-03 Bebe Le Strange.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-08 Strong, Strong Wind.m4a" "import/./Heart/The Essential 3.0/3-08 Strong, Strong Wind.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-01 Sylvan Song.m4a" "import/./Heart/The Essential 3.0/3-01 Sylvan Song.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-07 City's Burning.m4a" "import/./Heart/The Essential 3.0/3-07 City's Burning.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Heart/The Essential 3.0/3-06 Strange Euphoria.m4a" "import/./Heart/The Essential 3.0/3-06 Strange Euphoria.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Patty Griffin/Downtown Church/03 Little Fire (feat. Emmylou Harris).m4a" "import/./Patty Griffin/Downtown Church/03 Little Fire (feat. Emmylou Harris).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Kacey Musgraves/Same Trailer Different Park/11 Follow Your Arrow.m4a" "import/./Kacey Musgraves/Same Trailer Different Park/11 Follow Your Arrow.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Robert Earl Keen/The Rose Hotel/09 On and On.m4a" "import/./Robert Earl Keen/The Rose Hotel/09 On and On.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Fleet Foxes/Helplessness Blues/04 Battery Kinzie.m4a" "import/./Fleet Foxes/Helplessness Blues/04 Battery Kinzie.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Belle and Sebastian/Girls in Peacetime Want to Dance/07 The Everlasting Muse.m4a" "import/./Belle and Sebastian/Girls in Peacetime Want to Dance/07 The Everlasting Muse.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Anjulie/Boom - EP/01 Boom.m4a" "import/./Anjulie/Boom - EP/01 Boom.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Ben Harper & Relentless7/White Lies for Dark Times (Deluxe Version)/1-07 Fly One Time.m4a" "import/./Ben Harper & Relentless7/White Lies for Dark Times (Deluxe Version)/1-07 Fly One Time.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Olms/The Olms/04 Wanna Feel It.m4a" "import/./The Olms/The Olms/04 Wanna Feel It.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Olms/The Olms/04 Wanna Feel It 1.m4a" "import/./The Olms/The Olms/04 Wanna Feel It 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Styx_Roboto_2.MP3" "import/./Unknown Artist/Unknown Album/Styx_Roboto_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Backsliding.mp3" "import/./Unknown Artist/Unknown Album/Backsliding.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Moog.mp3" "import/./Unknown Artist/Unknown Album/Moog.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Bass1.mp3" "import/./Unknown Artist/Unknown Album/Bass1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/testout.wav" "import/./Unknown Artist/Unknown Album/testout.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Bass.mp3" "import/./Unknown Artist/Unknown Album/Bass.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/73.WAV" "import/./Unknown Artist/Unknown Album/73.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/George.mp3" "import/./Unknown Artist/Unknown Album/George.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Yes_1.MP3" "import/./Unknown Artist/Unknown Album/Yes_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/tambo_weird.mp3" "import/./Unknown Artist/Unknown Album/tambo_weird.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Phil_Collins_2.MP3" "import/./Unknown Artist/Unknown Album/Phil_Collins_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/bbc-21MHz.wav" "import/./Unknown Artist/Unknown Album/bbc-21MHz.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/System Audio 20110407 2108.mp3" "import/./Unknown Artist/Unknown Album/System Audio 20110407 2108.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/reset5.wav" "import/./Unknown Artist/Unknown Album/reset5.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Drums.mp3" "import/./Unknown Artist/Unknown Album/Drums.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/20130307 213945.m4a" "import/./Unknown Artist/Unknown Album/20130307 213945.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Huey_Lewis_1.MP3" "import/./Unknown Artist/Unknown Album/Huey_Lewis_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Horns 02-1.mp3" "import/./Unknown Artist/Unknown Album/Horns 02-1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Asia_1.MP3" "import/./Unknown Artist/Unknown Album/Asia_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Tron Bass 01 (mono)-2 1.mp3" "import/./Unknown Artist/Unknown Album/Tron Bass 01 (mono)-2 1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Slide Hi-2.mp3" "import/./Unknown Artist/Unknown Album/Slide Hi-2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Tron Bass 01 (mono)-2.mp3" "import/./Unknown Artist/Unknown Album/Tron Bass 01 (mono)-2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Crash & Ride 01.mp3" "import/./Unknown Artist/Unknown Album/Crash & Ride 01.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Styx_Roboto_1.MP3" "import/./Unknown Artist/Unknown Album/Styx_Roboto_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Agent Orange Intro 01 (mono)-1.mp3" "import/./Unknown Artist/Unknown Album/Agent Orange Intro 01 (mono)-1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/shaker_stereo4.mp3" "import/./Unknown Artist/Unknown Album/shaker_stereo4.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Country Pickin.mp3" "import/./Unknown Artist/Unknown Album/Country Pickin.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/reset7.wav" "import/./Unknown Artist/Unknown Album/reset7.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/69.WAV" "import/./Unknown Artist/Unknown Album/69.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/20121226 161746 1.m4a" "import/./Unknown Artist/Unknown Album/20121226 161746 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Meloflute.mp3" "import/./Unknown Artist/Unknown Album/Meloflute.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/67.WAV" "import/./Unknown Artist/Unknown Album/67.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Bass3.mp3" "import/./Unknown Artist/Unknown Album/Bass3.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/XDrum.mp3" "import/./Unknown Artist/Unknown Album/XDrum.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Tron Bass 01 (mono)-1-1.mp3" "import/./Unknown Artist/Unknown Album/Tron Bass 01 (mono)-1-1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/talkstop.wav" "import/./Unknown Artist/Unknown Album/talkstop.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/66.WAV" "import/./Unknown Artist/Unknown Album/66.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Phil_Collins_1.MP3" "import/./Unknown Artist/Unknown Album/Phil_Collins_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Styx_2.MP3" "import/./Unknown Artist/Unknown Album/Styx_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/71.WAV" "import/./Unknown Artist/Unknown Album/71.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Def_Lepard_2.MP3" "import/./Unknown Artist/Unknown Album/Def_Lepard_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/64.WAV" "import/./Unknown Artist/Unknown Album/64.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Clavichord.mp3" "import/./Unknown Artist/Unknown Album/Clavichord.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Duran_Duran_1.MP3" "import/./Unknown Artist/Unknown Album/Duran_Duran_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Slide Lo.mp3" "import/./Unknown Artist/Unknown Album/Slide Lo.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Drums2.mp3" "import/./Unknown Artist/Unknown Album/Drums2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/20130307 213945 1.m4a" "import/./Unknown Artist/Unknown Album/20130307 213945 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/code.wav" "import/./Unknown Artist/Unknown Album/code.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Live 6 Demo- Main Hook.mp3" "import/./Unknown Artist/Unknown Album/Live 6 Demo- Main Hook.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Melostring.mp3" "import/./Unknown Artist/Unknown Album/Melostring.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/20130307 214022 1.m4a" "import/./Unknown Artist/Unknown Album/20130307 214022 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/68.WAV" "import/./Unknown Artist/Unknown Album/68.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/testout 2.wav" "import/./Unknown Artist/Unknown Album/testout 2.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Bass2.mp3" "import/./Unknown Artist/Unknown Album/Bass2.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/reset3.wav" "import/./Unknown Artist/Unknown Album/reset3.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Crash & Ride 01-1.mp3" "import/./Unknown Artist/Unknown Album/Crash & Ride 01-1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/REMINDER.WAV" "import/./Unknown Artist/Unknown Album/REMINDER.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Guit.Drone.mp3" "import/./Unknown Artist/Unknown Album/Guit.Drone.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Rush - Vapor Trails Remixed.m4a" "import/./Unknown Artist/Unknown Album/Rush - Vapor Trails Remixed.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Men_at_Work_2.MP3" "import/./Unknown Artist/Unknown Album/Men_at_Work_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Pat_Benatar_2.MP3" "import/./Unknown Artist/Unknown Album/Pat_Benatar_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/testout 3.wav" "import/./Unknown Artist/Unknown Album/testout 3.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Pat_Benatar_1.MP3" "import/./Unknown Artist/Unknown Album/Pat_Benatar_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Strings.mp3" "import/./Unknown Artist/Unknown Album/Strings.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Tron Bass 01 (mono).mp3" "import/./Unknown Artist/Unknown Album/Tron Bass 01 (mono).mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/sample2ch.m4a" "import/./Unknown Artist/Unknown Album/sample2ch.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/74.WAV" "import/./Unknown Artist/Unknown Album/74.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/65.WAV" "import/./Unknown Artist/Unknown Album/65.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Country Dist.mp3" "import/./Unknown Artist/Unknown Album/Country Dist.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/phonenop.wav" "import/./Unknown Artist/Unknown Album/phonenop.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Huey_Lewis_2.MP3" "import/./Unknown Artist/Unknown Album/Huey_Lewis_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Bridge Riff.mp3" "import/./Unknown Artist/Unknown Album/Bridge Riff.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Melotron.mp3" "import/./Unknown Artist/Unknown Album/Melotron.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Horns 01.mp3" "import/./Unknown Artist/Unknown Album/Horns 01.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/testout 1.wav" "import/./Unknown Artist/Unknown Album/testout 1.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Loverboy_2.MP3" "import/./Unknown Artist/Unknown Album/Loverboy_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Bells-1.mp3" "import/./Unknown Artist/Unknown Album/Bells-1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/70.WAV" "import/./Unknown Artist/Unknown Album/70.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Asia_2.MP3" "import/./Unknown Artist/Unknown Album/Asia_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Paul.mp3" "import/./Unknown Artist/Unknown Album/Paul.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Men_at_Work_1.MP3" "import/./Unknown Artist/Unknown Album/Men_at_Work_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/72.WAV" "import/./Unknown Artist/Unknown Album/72.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/busy.wav" "import/./Unknown Artist/Unknown Album/busy.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Sth Rock.mp3" "import/./Unknown Artist/Unknown Album/Sth Rock.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/ring_switch.wav" "import/./Unknown Artist/Unknown Album/ring_switch.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Styx_1.MP3" "import/./Unknown Artist/Unknown Album/Styx_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Loverboy_1.MP3" "import/./Unknown Artist/Unknown Album/Loverboy_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/20121226 161746.m4a" "import/./Unknown Artist/Unknown Album/20121226 161746.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/ripples.wav" "import/./Unknown Artist/Unknown Album/ripples.wav"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Ratt_1.MP3" "import/./Unknown Artist/Unknown Album/Ratt_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/20130307 214022.m4a" "import/./Unknown Artist/Unknown Album/20130307 214022.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Yes_2.MP3" "import/./Unknown Artist/Unknown Album/Yes_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Duran_Duran_2.MP3" "import/./Unknown Artist/Unknown Album/Duran_Duran_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Ratt_2.MP3" "import/./Unknown Artist/Unknown Album/Ratt_2.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/02-08-2015_00-08_msg94215.mp3" "import/./Unknown Artist/Unknown Album/02-08-2015_00-08_msg94215.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/sample.m4a" "import/./Unknown Artist/Unknown Album/sample.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Jimi.mp3" "import/./Unknown Artist/Unknown Album/Jimi.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Crash & Ride 02-1.mp3" "import/./Unknown Artist/Unknown Album/Crash & Ride 02-1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Funk1.mp3" "import/./Unknown Artist/Unknown Album/Funk1.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Crash R.mp3" "import/./Unknown Artist/Unknown Album/Crash R.mp3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/Def_Lepard_1.MP3" "import/./Unknown Artist/Unknown Album/Def_Lepard_1.MP3"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Unknown Artist/Unknown Album/75.WAV" "import/./Unknown Artist/Unknown Album/75.WAV"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./The Airborne Toxic Event/Sometime Around Midnight (Acoustic Version) - Single/01 Sometime Around Midnight (Acoustic Version).m4p" "import/./The Airborne Toxic Event/Sometime Around Midnight (Acoustic Version) - Single/01 Sometime Around Midnight (Acoustic Version).m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./John Cougar/American Fool (Remastered)/03 Hand to Hold On to.m4p" "import/./John Cougar/American Fool (Remastered)/03 Hand to Hold On to.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Orchestra Baobab/Made In Dakar/01 Pape Ndiaye 2.m4p" "import/./Orchestra Baobab/Made In Dakar/01 Pape Ndiaye 2.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Hiss Golden Messenger/Lateness of Dancers/02 Saturday's Song.m4a" "import/./Hiss Golden Messenger/Lateness of Dancers/02 Saturday's Song.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Matt Nathanson/Faster - Single/01 Faster.m4p" "import/./Matt Nathanson/Faster - Single/01 Faster.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Nataly Dawn/Please Don't Scream - Single/03 Please Don't Scream 2.m4a" "import/./Nataly Dawn/Please Don't Scream - Single/03 Please Don't Scream 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Nataly Dawn/Please Don't Scream - Single/03 Please Don't Scream 1.m4a" "import/./Nataly Dawn/Please Don't Scream - Single/03 Please Don't Scream 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/iTunes Holiday Sampler/03 Silent Night 2.m4a" "import/./Compilations/iTunes Holiday Sampler/03 Silent Night 2.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/iTunes Holiday Sampler/03 Silent Night 1.m4a" "import/./Compilations/iTunes Holiday Sampler/03 Silent Night 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/iTunes Holiday Sampler/09 God Rest Ye Merry Gentlemen 1.m4a" "import/./Compilations/iTunes Holiday Sampler/09 God Rest Ye Merry Gentlemen 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/4_ John Paul George Ringo - EP/03 Let It Down.m4a" "import/./Compilations/4_ John Paul George Ringo - EP/03 Let It Down.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/4_ John Paul George Ringo - EP/02 Call Me Back Again.m4a" "import/./Compilations/4_ John Paul George Ringo - EP/02 Call Me Back Again.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/4_ John Paul George Ringo - EP/01 Love.m4a" "import/./Compilations/4_ John Paul George Ringo - EP/01 Love.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/4_ John Paul George Ringo - EP/04 Walk With You.m4a" "import/./Compilations/4_ John Paul George Ringo - EP/04 Walk With You.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Compilations/Dance (RED) Save Lives, Vol. 2/20 Slow Motion (feat. HAERTS).m4a" "import/./Compilations/Dance (RED) Save Lives, Vol. 2/20 Slow Motion (feat. HAERTS).m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Motopony/Motopony (Bonus Track Version)/02 King of Diamonds.m4a" "import/./Motopony/Motopony (Bonus Track Version)/02 King of Diamonds.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Motopony/Motopony (Bonus Track Version)/02 King of Diamonds 1.m4a" "import/./Motopony/Motopony (Bonus Track Version)/02 King of Diamonds 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Peter Gabriel/So/09 In Your Eyes 1.m4p" "import/./Peter Gabriel/So/09 In Your Eyes 1.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Say Hi/Um, Uh Oh (Bonus Track Version)/01 Dots On Maps.m4a" "import/./Say Hi/Um, Uh Oh (Bonus Track Version)/01 Dots On Maps.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Cristina/De los Pies Hasta la Frente/03 Mucha Mujer para Ti.m4a" "import/./Cristina/De los Pies Hasta la Frente/03 Mucha Mujer para Ti.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Gregory Alan Isakov/The Weatherman/04 Living Proof.m4a" "import/./Gregory Alan Isakov/The Weatherman/04 Living Proof.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Gregory Alan Isakov/The Weatherman/04 Living Proof 1.m4a" "import/./Gregory Alan Isakov/The Weatherman/04 Living Proof 1.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./London Philharmonic Orchestra, Renée Fleming & Sir Charles Mackerras/Renée Fleming/07 La Wally, Drama Lirica in Quattro Atti_ Ebben_ Ne Andrò Lontana.m4p" "import/./London Philharmonic Orchestra, Renée Fleming & Sir Charles Mackerras/Renée Fleming/07 La Wally, Drama Lirica in Quattro Atti_ Ebben_ Ne Andrò Lontana.m4p"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Angus & Julia Stone/A Book Like This/01 Mango Tree.m4a" "import/./Angus & Julia Stone/A Book Like This/01 Mango Tree.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Travis/Ode to J. Smith/06 Last Words.m4a" "import/./Travis/Ode to J. Smith/06 Last Words.m4a"
scp "dan@ubuntu:/mnt/user_data/dan_data/Music/iTunes/Music/./Neko Case/People Got a Lotta Nerve - Single/01 People Got a Lotta Nerve.m4a" "import/./Neko Case/People Got a Lotta Nerve - Single/01 People Got a Lotta Nerve.m4a"
